/**
 * ORDERS MOCK DATA
 *
 * This file is the ONLY place with hardcoded data.
 * When connecting to a real API:
 *   1. Replace MOCK_ORDERS with API response shape
 *   2. Update useOrders.js fetchOrders() only
 *   3. Nothing else in the widget needs to change
 *
 * Data shape matches expected API contract:
 * GET /api/orders → Order[]
 */

// ── Tab filter predicates ──────────────────────────────────────────────────
// Basket children (basketId !== null && !isBasketParent) are ONLY visible
// in the 'basket' tab — all other tab predicates exclude them so they never
// appear as orphan flat rows.

export const TAB_FILTER = {
  open:     o => o.status === 'pending' && !o.gtt && (!o.basketId || o.isBasketParent),
  today:    o => !o.gtt && (!o.basketId || o.isBasketParent),
  executed: o => o.status === 'executed' && (!o.basketId || o.isBasketParent),
  cancelled:o => o.status === 'cancelled' && (!o.basketId || o.isBasketParent),
  rejected: o => o.status === 'rejected' && (!o.basketId || o.isBasketParent),
  gtt:      o => o.gtt === true,
  basket:   o => o.isBasketParent === true,
  all:      o => !o.basketId || o.isBasketParent,
};

// ── Default visible columns ────────────────────────────────────────────────
export const DEFAULT_COLUMNS = [
  { id: 'time',       label: 'Time',       visible: true,  pinned: false },
  { id: 'instrument', label: 'Instrument', visible: true,  pinned: true  },
  { id: 'side',       label: 'B/S',        visible: true,  pinned: false },
  { id: 'qty',        label: 'Qty',        visible: true,  pinned: false },
  { id: 'price',      label: 'Price',      visible: true,  pinned: false },
  { id: 'trigger',    label: 'Trigger',    visible: true,  pinned: false },
  { id: 'orderType',  label: 'Order Type', visible: true,  pinned: false },
  { id: 'product',    label: 'Product',    visible: true,  pinned: false },
  { id: 'status',     label: 'Status',     visible: true,  pinned: false },
  { id: 'filledQty',  label: 'Filled',     visible: true,  pinned: false },
  { id: 'avgPrice',   label: 'Avg Price',  visible: true,  pinned: false },
];

// ── Mock orders ────────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  // ── Open / Pending ────────────────────────────────────────────────
  {
    id: 'ORD001',
    time: '09:17:42',
    symbol: 'RELIANCE',
    exchange: 'NSE',
    segment: 'equity',
    side: 'buy',
    qty: 10,
    price: 2945.00,
    trigger: null,
    orderType: 'LIMIT',
    product: 'CNC',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },
  {
    id: 'ORD002',
    time: '09:19:05',
    symbol: 'NIFTY 24500 CE',
    exchange: 'NFO',
    segment: 'fo',
    side: 'sell',
    qty: 50,
    price: 128.50,
    trigger: null,
    orderType: 'LIMIT',
    product: 'NRML',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },
  {
    id: 'ORD003',
    time: '09:22:30',
    symbol: 'GOLD23OCT',
    exchange: 'MCX',
    segment: 'commodity',
    side: 'buy',
    qty: 1,
    price: 61800.00,
    trigger: null,
    orderType: 'SL-M',
    product: 'NRML',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },

  // ── Executed ──────────────────────────────────────────────────────
  {
    id: 'ORD004',
    time: '09:15:12',
    symbol: 'INFY',
    exchange: 'NSE',
    segment: 'equity',
    side: 'buy',
    qty: 25,
    price: 0,
    trigger: null,
    orderType: 'MARKET',
    product: 'MIS',
    status: 'executed',
    filledQty: 25,
    avgPrice: 1427.35,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },
  {
    id: 'ORD005',
    time: '09:16:00',
    symbol: 'BANKNIFTY 47000 PE',
    exchange: 'NFO',
    segment: 'fo',
    side: 'buy',
    qty: 25,
    price: 310.00,
    trigger: null,
    orderType: 'LIMIT',
    product: 'NRML',
    status: 'executed',
    filledQty: 25,
    avgPrice: 309.80,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },
  {
    id: 'ORD006',
    time: '09:20:45',
    symbol: 'TCS',
    exchange: 'BSE',
    segment: 'equity',
    side: 'sell',
    qty: 5,
    price: 3820.00,
    trigger: null,
    orderType: 'LIMIT',
    product: 'CNC',
    status: 'executed',
    filledQty: 5,
    avgPrice: 3821.50,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },

  // ── Cancelled ─────────────────────────────────────────────────────
  {
    id: 'ORD007',
    time: '09:18:20',
    symbol: 'HDFC BANK',
    exchange: 'NSE',
    segment: 'equity',
    side: 'buy',
    qty: 15,
    price: 1680.00,
    trigger: null,
    orderType: 'LIMIT',
    product: 'CNC',
    status: 'cancelled',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },
  {
    id: 'ORD008',
    time: '09:21:10',
    symbol: 'SILVER23OCT',
    exchange: 'MCX',
    segment: 'commodity',
    side: 'sell',
    qty: 30,
    price: 75200.00,
    trigger: null,
    orderType: 'SL',
    product: 'NRML',
    status: 'cancelled',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },

  // ── Rejected ──────────────────────────────────────────────────────
  {
    id: 'ORD009',
    time: '09:15:55',
    symbol: 'NIFTY 23000 PE',
    exchange: 'NFO',
    segment: 'fo',
    side: 'sell',
    qty: 75,
    price: 2.50,
    trigger: null,
    orderType: 'LIMIT',
    product: 'NRML',
    status: 'rejected',
    filledQty: 0,
    avgPrice: null,
    rejectReason: 'Insufficient margin',
    gtt: false,
    basketId: null,
    isBasketParent: false,
  },

  // ── GTT / OCO ────────────────────────────────────────────────────
  {
    id: 'ORD010',
    time: '08:30:00',
    symbol: 'WIPRO',
    exchange: 'NSE',
    segment: 'equity',
    side: 'buy',
    qty: 100,
    price: 430.00,
    trigger: 432.00,
    orderType: 'GTT',
    product: 'CNC',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: true,
    gttType: 'single',
    basketId: null,
    isBasketParent: false,
  },
  {
    id: 'ORD011',
    time: '08:45:00',
    symbol: 'RELIANCE',
    exchange: 'NSE',
    segment: 'equity',
    side: 'sell',
    qty: 10,
    price: 3000.00,
    trigger: 2880.00,
    orderType: 'OCO',
    product: 'CNC',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: true,
    gttType: 'oco',
    stopLoss: 2880.00,
    target: 3000.00,
    basketId: null,
    isBasketParent: false,
  },

  // ── Basket (parent + children) ────────────────────────────────────
  {
    id: 'ORD012',
    time: '09:17:00',
    symbol: 'NIFTY Options Straddle',
    exchange: 'NFO',
    segment: 'fo',
    side: 'buy',
    qty: 2,
    price: null,
    trigger: null,
    orderType: 'BASKET',
    product: 'NRML',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: 'BSKT001',
    isBasketParent: true,
    childCount: 2,
  },
  {
    id: 'ORD012A',
    time: '09:17:00',
    symbol: 'NIFTY 24500 CE',
    exchange: 'NFO',
    segment: 'fo',
    side: 'buy',
    qty: 50,
    price: 128.50,
    trigger: null,
    orderType: 'MARKET',
    product: 'NRML',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: 'BSKT001',
    isBasketParent: false,
  },
  {
    id: 'ORD012B',
    time: '09:17:00',
    symbol: 'NIFTY 24500 PE',
    exchange: 'NFO',
    segment: 'fo',
    side: 'buy',
    qty: 50,
    price: 122.00,
    trigger: null,
    orderType: 'MARKET',
    product: 'NRML',
    status: 'pending',
    filledQty: 0,
    avgPrice: null,
    gtt: false,
    basketId: 'BSKT001',
    isBasketParent: false,
  },
];
