/**
 * POSITIONS MOCK DATA
 *
 * This file is the ONLY place with hardcoded data.
 * When connecting to a real API:
 *   1. Replace MOCK_POSITIONS with API response
 *   2. Update usePositions.js fetchPositions() only
 *   3. Nothing else in the widget changes
 *
 * Data shape matches expected API contract:
 * GET /api/positions →
 *   { equity: [], fno: [], commodity: [] }
 */

export const MOCK_POSITIONS = {
  equity: [
    {
      id: 'POS001',
      symbol:        'RELIANCE',
      exchange:      'NSE',
      product:       'CNC',
      direction:     'buy',
      qty:           25,
      avgPrice:      2845.60,
      mktPrice:      2912.35,
      dayChange:     18.20,
      dayChangePct:  0.63,
      pnlAbs:        1668.75,
      pnlPct:        2.34,
      breakeven:     2845.60,
      qtyBought:     25,
      qtySold:       0,
      dayHigh:       2930.00,
      dayLow:        2840.00,
      marginConsumed: 71140,
      mtmPnl:        1668.75,
      greeks:        null,
    },
    {
      id: 'POS002',
      symbol:        'INFY',
      exchange:      'NSE',
      product:       'MIS',
      direction:     'sell',
      qty:           50,
      avgPrice:      1782.40,
      mktPrice:      1768.90,
      dayChange:     -6.50,
      dayChangePct:  -0.37,
      pnlAbs:        675.00,
      pnlPct:        0.76,
      breakeven:     1782.40,
      qtyBought:     0,
      qtySold:       50,
      dayHigh:       1795.00,
      dayLow:        1760.00,
      marginConsumed: 89120,
      mtmPnl:        675.00,
      greeks:        null,
    },
    {
      id: 'POS003',
      symbol:        'HDFCBANK',
      exchange:      'NSE',
      product:       'CNC',
      direction:     'buy',
      qty:           15,
      avgPrice:      1640.00,
      mktPrice:      1598.75,
      dayChange:     -12.25,
      dayChangePct:  -0.76,
      pnlAbs:        -618.75,
      pnlPct:        -2.51,
      breakeven:     1640.00,
      qtyBought:     15,
      qtySold:       0,
      dayHigh:       1655.00,
      dayLow:        1590.00,
      marginConsumed: 24600,
      mtmPnl:        -618.75,
      greeks:        null,
    },
    {
      id: 'POS004',
      symbol:        'TATAMOTORS',
      exchange:      'BSE',
      product:       'MIS',
      direction:     'buy',
      qty:           100,
      avgPrice:      845.20,
      mktPrice:      858.90,
      dayChange:     4.70,
      dayChangePct:  0.55,
      pnlAbs:        1370.00,
      pnlPct:        1.62,
      breakeven:     845.20,
      qtyBought:     100,
      qtySold:       0,
      dayHigh:       862.00,
      dayLow:        839.00,
      marginConsumed: 84520,
      mtmPnl:        1370.00,
      greeks:        null,
    },
    {
      id: 'POS005',
      symbol:        'TCS',
      exchange:      'NSE',
      product:       'CNC',
      direction:     'buy',
      qty:           10,
      avgPrice:      3920.00,
      mktPrice:      3945.25,
      dayChange:     25.25,
      dayChangePct:  0.64,
      pnlAbs:        252.50,
      pnlPct:        0.64,
      breakeven:     3920.00,
      qtyBought:     10,
      qtySold:       0,
      dayHigh:       3960.00,
      dayLow:        3900.00,
      marginConsumed: 39200,
      mtmPnl:        252.50,
      greeks:        null,
    },
  ],

  fno: [
    {
      id: 'POS006',
      symbol:        'NIFTY 25600 CE',
      exchange:      'NFO',
      product:       'MIS',
      direction:     'buy',
      qty:           75,
      avgPrice:      148.50,
      mktPrice:      162.75,
      dayChange:     8.20,
      dayChangePct:  5.04,
      pnlAbs:        1068.75,
      pnlPct:        9.60,
      breakeven:     25748.50,
      qtyBought:     75,
      qtySold:       0,
      dayHigh:       170.00,
      dayLow:        138.00,
      marginConsumed: 55000,
      mtmPnl:        1068.75,
      greeks: {
        delta: 0.42,
        gamma: 0.0018,
        theta: -12.4,
        vega:  28.6,
      },
    },
    {
      id: 'POS007',
      symbol:        'BANKNIFTY 48000 PE',
      exchange:      'NFO',
      product:       'NRML',
      direction:     'sell',
      qty:           30,
      avgPrice:      320.00,
      mktPrice:      289.50,
      dayChange:     -15.00,
      dayChangePct:  -4.93,
      pnlAbs:        915.00,
      pnlPct:        9.53,
      breakeven:     47680.00,
      qtyBought:     0,
      qtySold:       30,
      dayHigh:       345.00,
      dayLow:        275.00,
      marginConsumed: 180000,
      mtmPnl:        915.00,
      greeks: {
        delta: -0.38,
        gamma: 0.0012,
        theta: -18.2,
        vega:  35.1,
      },
    },
    {
      id: 'POS008',
      symbol:        'NIFTY 25500 PE',
      exchange:      'NFO',
      product:       'MIS',
      direction:     'sell',
      qty:           50,
      avgPrice:      95.00,
      mktPrice:      78.50,
      dayChange:     -6.50,
      dayChangePct:  -7.65,
      pnlAbs:        825.00,
      pnlPct:        17.37,
      breakeven:     25405.00,
      qtyBought:     0,
      qtySold:       50,
      dayHigh:       108.00,
      dayLow:        72.00,
      marginConsumed: 47500,
      mtmPnl:        825.00,
      greeks: {
        delta: -0.28,
        gamma: 0.0009,
        theta: -8.6,
        vega:  22.4,
      },
    },
    {
      id: 'POS009',
      symbol:        'RELIANCE 2900 CE',
      exchange:      'NFO',
      product:       'NRML',
      direction:     'buy',
      qty:           40,
      avgPrice:      42.00,
      mktPrice:      38.25,
      dayChange:     -1.75,
      dayChangePct:  -4.37,
      pnlAbs:        -150.00,
      pnlPct:        -8.93,
      breakeven:     2942.00,
      qtyBought:     40,
      qtySold:       0,
      dayHigh:       48.00,
      dayLow:        36.00,
      marginConsumed: 16800,
      mtmPnl:        -150.00,
      greeks: {
        delta: 0.31,
        gamma: 0.0022,
        theta: -9.8,
        vega:  18.9,
      },
    },
  ],

  commodity: [
    {
      id: 'POS010',
      symbol:        'GOLD',
      exchange:      'MCX',
      product:       'NRML',
      direction:     'buy',
      qty:           1,
      avgPrice:      72400.00,
      mktPrice:      72840.00,
      dayChange:     440.00,
      dayChangePct:  0.61,
      pnlAbs:        440.00,
      pnlPct:        0.61,
      breakeven:     72400.00,
      qtyBought:     1,
      qtySold:       0,
      dayHigh:       73000.00,
      dayLow:        72100.00,
      marginConsumed: 72400,
      mtmPnl:        440.00,
      greeks:        null,
    },
    {
      id: 'POS011',
      symbol:        'SILVER',
      exchange:      'MCX',
      product:       'NRML',
      direction:     'buy',
      qty:           2,
      avgPrice:      89500.00,
      mktPrice:      90120.00,
      dayChange:     310.00,
      dayChangePct:  0.35,
      pnlAbs:        1240.00,
      pnlPct:        0.69,
      breakeven:     89500.00,
      qtyBought:     2,
      qtySold:       0,
      dayHigh:       90800.00,
      dayLow:        89200.00,
      marginConsumed: 89500,
      mtmPnl:        1240.00,
      greeks:        null,
    },
    {
      id: 'POS012',
      symbol:        'CRUDEOIL',
      exchange:      'MCX',
      product:       'MIS',
      direction:     'sell',
      qty:           3,
      avgPrice:      6840.00,
      mktPrice:      6920.00,
      dayChange:     80.00,
      dayChangePct:  1.17,
      pnlAbs:        -240.00,
      pnlPct:        -1.17,
      breakeven:     6840.00,
      qtyBought:     0,
      qtySold:       3,
      dayHigh:       6960.00,
      dayLow:        6800.00,
      marginConsumed: 20520,
      mtmPnl:        -240.00,
      greeks:        null,
    },
  ],
};

/**
 * SUMMARY MOCK
 * In production: computed from positions or
 * returned from GET /api/portfolio/summary
 */
export const MOCK_SUMMARY = {
  overallPnl:    4218.50,
  unrealisedPnl: 3140.25,
  realisedPnl:   1078.25,
  dayChange:     -312.00,
  marginUsed:    62,
  marginTotal:   500000,
};

/**
 * DEFAULT COLUMN CONFIG
 * In production: persist to user preferences API
 * GET/POST /api/user/preferences/positions-columns
 */
export const DEFAULT_COLUMNS = [
  { id: 'instrument', label: 'Instrument',  pinned: true,  visible: true  },
  { id: 'direction',  label: 'Direction',   pinned: false, visible: true  },
  { id: 'qty',        label: 'Qty',         pinned: false, visible: true  },
  { id: 'avgPrice',   label: 'Avg Price',   pinned: false, visible: true  },
  { id: 'mktPrice',   label: 'MKT Price',   pinned: false, visible: true  },
  { id: 'pnl',        label: 'P&L',         pinned: false, visible: true  },
  { id: 'dayChange',  label: "Day's Change", pinned: false, visible: true  },
  { id: 'returns',    label: 'Returns %',   pinned: false, visible: true  },
];
